### PR TITLE
Support Mixed-dimension Tables in The Forward Pass

### PR DESCRIPTION
**Pull request by weihanmines**
Implemented suggested patterns (Carlus) in the forward kernel. 
d9362792-dc09-4621-99f3-d545a74ff2ef

### CODE REVIEW

**Comment by liligwu** [comment]
All embedding tests passed.
[Uploading 20221013_test_log_pyt_fbgemm_embedding_bag_synData_origin_mixed-dim-new.txt…]()

**Review by carlushuang — APPROVED** [review]
LGTM

**Review by dllehr-amd — APPROVED** [review]
LGTM!

**Review by HaiShaw — CHANGES_REQUESTED** [review]
Please remove mixed dimension guard, and test the functionality if all went well. Thanks!

**Comment by HaiShaw** [comment]
Also - regarding the load/store pattern, why not use 'floatx4', 'floatx2', 'float', 'half' in descending (priority) order to achieve minimum number of issues?

**Comment by weihanmines** [comment]
> Please remove mixed dimension guard, and test the functionality if all went well. Thanks!

done in the latest commit.

**Pull request merged**
